workflows:
  ios-build:
    name: iOS build unsigned app
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install && cd ..
      # 自动修改pbxproj，写入一个占位Team，绕过Flutter Team校验
      - sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = XXXXXXXX;/' ios/Runner.xcodeproj/project.pbxproj
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/**/*.app
